# Generated by Django 6.0.4 on 2026-04-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_rename_session_question_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_answer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
