# Generated by Django 6.0.4 on 2026-04-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at']},
        ),
    ]
